//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikGridMVC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string Price { get; set; }
        public Nullable<int> InStock { get; set; }
        public string Category { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Country { get; set; }
        public Nullable<int> Units { get; set; }
        public string ProductName { get; set; }
    }
}
